FROM mysql:latest

ENV MYSQL_ROOT_USER=root
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_ROOT_HOST=172.*.*.*
ENV MYSQL_ALLOW_EMPTY_PASSWORD=true

COPY src/main/resources/db-scripts/ /docker-entrypoint-initdb.d/
